INSERT INTO flowStates (state, keyword, valueAction, nextstate) VALUES 
    (0, 'PAYMENTS', null, 1),
    (1, 'ANY', null, 2),
    (2, 'ANY', null, 3),
    (3, 'ANY', null, 4),
    (4, 'ANY', null, 5),
    (5, 'ANY', null, 0),
    (6, 'ANY', "BUYER", 7),
    (7, 'ANY', "SELLER", 8),
    (8, 'BUYER', null, 9),
    (8, 'SELLER', null, 10),
    (9, 'ANY', "PRICE", 11),
    (10, 'ANY', "FILE", 11),
    (11, 'YES', null, 12),
    (11, 'NO', null, 22),
    (12, 'BUYER', null, 13),
    (12, 'SELLER', null, 14),
    (12, 'PRICE', null, 15),
    (13, 'ANY', "BUYER", 11),
    (14, 'ANY', "SELLER", 11),
    (15, 'ANY', "PRICE", 11),
    (22, 'ANY', null, 0),
    (0, 'TRANSACTION', null, 6);
    
INSERT INTO messages(state, messageType, message, options) VALUES 
    (0, 'button', 'Hi, welcome to escrow bot. Respond PAYMENTS if you would like to enter payment info or TRANSACTION if you would like to start a new transaction', "PAYMENTS,TRANSACTION"),
    (1, 'text', 'You selected PAYMENTS. You can respond HELP to get a help message or ABORT to exit the process at any time. Please enter the full name that appears on the card.', ""),
    (2, 'text', 'Enter the card number.', ""),
    (3, 'text', 'Enter the expiration date.', ""),
    (4, 'text', 'Enter the CVV.', ""),
    (5, 'text', 'Enter the zip code.', ""),
    (6, 'text', 'You selected TRANSACTION. You can respond HELP to get a help message, SUMMARY to see a summary of the current transaction, and ABORT to exit the process at any time. Please enter the full name of the buyer.', ''),
    (7, 'text', 'Enter the full name of the seller of this transaction.', ''),
    (8, 'button', 'Are you the buyer or seller?', 'BUYER,SELLER'),
    (9, 'text', 'Please enter the price of the transaction.', ''),
    (10, 'text', 'Please attach a PDF version of the item to be exchanged', ''),
    (11, 'text', 'The transaction is complete. Would you like to edit any information?', 'YES,NO'),
    (12, 'text', 'What would you like to edit about your transaction?', 'BUYER,SELLER,PRICE'),
    (13, 'text', 'Enter a new buyer name', ''),
    (14, 'text', 'Enter a new seller name', ''),
    (15, 'text', 'Enter a new price', ''),
    (22, 'button', 'Thank you for using Escrow bot! Type anything to start a new transaction.', ''),
    (911, 'text', 'This bot helps you secure your marketplace transactions via an escrow model. The bot will tell you everything you need to know at each stage of the conversation. Type ABORT at any point to cancel your transaction.', ''), 
    (666, 'text', 'Your transaction was aborted. To restart the conversation, simply message the bot anything.', '');